import { useRef, useState } from "react";
import { Check, FileUp, ShieldCheck, UploadCloud } from "lucide-react";
import { PageTitle } from "../components/PageTitle";
import { demoCandidate } from "../lib/demoMatch";

const supported = ["application/pdf", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"];

export function CandidatePage() {
  const input = useRef<HTMLInputElement>(null);
  const [file, setFile] = useState<File | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const selectFile = (next: File | undefined) => {
    if (!next) return;
    if (!supported.includes(next.type) || next.size > 10 * 1024 * 1024) { setMessage("Use a PDF or DOCX file no larger than 10 MB."); return; }
    setFile(next); setMessage("Resume accepted locally. Upload will be sent to /api/candidates/upload-resume when FR-02 is available.");
  };
  return <main className="mx-auto max-w-[1200px] space-y-6 px-5 py-6 lg:px-8"><PageTitle eyebrow="Candidate workspace" title="Make your skills legible to the right roles." detail="Your data becomes a structured profile: experience and skills for matching, with protected personal details excluded from scoring." /><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_330px]"><section className="glass-panel wave-violet rounded-2xl p-5"><div className="flex items-center gap-2"><FileUp className="h-4 w-4 text-spectral-violet" /><h2 className="font-semibold">Resume ingestion</h2></div><button onClick={() => input.current?.click()} onDrop={(e) => { e.preventDefault(); selectFile(e.dataTransfer.files[0]); }} onDragOver={(e) => e.preventDefault()} className="mt-5 flex min-h-56 w-full flex-col items-center justify-center rounded-xl border border-dashed border-spectral-violet/40 bg-spectral-violet/5 px-6 text-center transition hover:border-spectral-emerald/55 hover:bg-spectral-emerald/5"><UploadCloud className="h-8 w-8 text-spectral-violet" /><strong className="mt-3 text-sm">Drop your PDF or DOCX here</strong><span className="mt-1 text-xs text-white/40">or select it from your device · maximum 10 MB</span><input ref={input} type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" className="hidden" onChange={(e) => selectFile(e.target.files?.[0])} /></button>{message && <p className="mt-4 rounded-lg border border-spectral-emerald/25 bg-spectral-emerald/5 px-3 py-2 text-xs text-spectral-emerald">{message}</p>}{file && <div className="mt-4 flex items-center justify-between rounded-lg border border-white/10 bg-black/15 px-3 py-3 text-sm"><span className="truncate">{file.name}</span><span className="font-mono text-xs text-white/35">{(file.size / 1024 / 1024).toFixed(2)} MB</span></div>}</section><aside className="space-y-4"><div className="glass-panel rounded-2xl p-5"><p className="section-label semantic-label">Profile preview</p><h2 className="mt-3 text-lg font-semibold">{demoCandidate.role}</h2><p className="text-sm text-white/40">{demoCandidate.specialisation} · {demoCandidate.location}</p><div className="mt-4 flex flex-wrap gap-2">{demoCandidate.skills.map((skill) => <span key={skill} className="rounded-md bg-white/5 px-2 py-1 font-mono text-[10px] text-spectral-emerald">{skill}</span>)}</div></div><div className="glass-panel wave-amber rounded-2xl p-5"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-spectral-amber" /><h2 className="text-sm font-semibold">Privacy by design</h2></div><ul className="mt-4 space-y-3 text-xs text-white/55"><li className="flex gap-2"><Check className="h-3.5 w-3.5 shrink-0 text-spectral-amber" />Names, age, gender and contact details excluded from scoring</li><li className="flex gap-2"><Check className="h-3.5 w-3.5 shrink-0 text-spectral-amber" />Only role-relevant evidence reaches the matching engine</li></ul></div></aside></div></main>;
}
